spring:
  application:
    name: CouponRush

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/coupon
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 1000
      validation-timeout: 1000
      max-lifetime: 180000
  transaction:
    default-timeout: 2

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8080